### PR TITLE
add profile detail, event list, event detail, profile list

### PR DESCRIPTION
**Pull request by zebapy**
@imcbride the following items are ready for you to look at and implement 

- school/midd-profile-detail
  - faq/accordion/course list has revised markup
- school/midd-event-detail
- school/midd-event-list
- https://github.com/middlebury/drupal8/commit/e8a43bbb8be2990c9c9c11f9cb05be127ec56af0 needs revert on production to match https://github.com/middlebury/midd-frontend/commit/2791c035f9e03346ec9dae016b1ff660d84d6b1c
- edit: profile list is ready

### CODE REVIEW

**Comment by imcbride** [comment]
On the event detail, please add an opening paragraph and a place to print the admission price.

**Comment by imcbride** [comment]
25Live does not have an opening paragraph. The event content type on the Institute site does.

**Comment by kettlestitch** [comment]
So do we need it then?

________________________________

**Comment by imcbride** [comment]
That's up to you. We added it to the Institute site, so there was some desire to have it, but I can also remove it if that's what you would prefer.

**Comment by kettlestitch** [comment]
I am just thinking that if the ability to create events in the site is removed for the general public - then we are really limited to what is coming over from R25. Seems like it would be a field that won't be used enough to warrant having. Just a thought.

________________________________

**Comment by imcbride** [comment]
In our last meeting with EM and the Arts we left open the option that their office would be able to manually edit events. I believe we also said that Communications would be able to manually edit them, if there were events like Commencement where we wanted to include more information than is available in 25Live.

But I can remove the opening paragraph field if you don't want to include it for events.

**Comment by imcbride** [comment]
Adding this as a separate note: we also need (I think?) a place to display speaker information.

So the missing fields are definitely admission price, probably speakers, and maybe opening paragraph.

**Comment by kettlestitch** [comment]
Are speakers coming over from R25?

________________________________

**Comment by imcbride** [comment]
No, those are added manually as references to profiles.

**Comment by kettlestitch** [comment]
Until we have locked down requires from the events team, I think we should leave out non-R25 fields.


Is it easier to remove them later? Or to add them now and remove them?


Given we haven't wrapped up those conversations, its unclear how important these elements are.

________________________________

**Comment by zebapy** [comment]
@imcbride is the open/closed to public value always populated or sometimes null?

**Comment by imcbride** [comment]
@zebapy The open/closed to the public field _should_ never be null, but I still have a check for it just in case so there's no error thrown if the event node is somehow created in a way that the boolean field returns a blank value. https://github.com/middlebury/drupal8/blob/profile-event-list-detail/web/themes/custom/middlebury_theme/templates/node--event.html.twig#L44

**Pull request merged**
