### PR TITLE
Flowchart

### PR DESCRIPTION
**Pull request by imcbride**
To go along with https://github.com/middlebury/drupal8/pull/1144

Test site available at http://saw.middlebury.edu/~imcbride/office/
Test content http://saw.middlebury.edu/~imcbride/office/information-technology-services/services/web-forms

I have noticed that the styles in this add a top border to header menu items, which should be addressed before this is merged and deployed.

image

### CODE REVIEW

**Comment by imcbride** [comment]
I've refreshed my test site now that you've merged in the develop branch and the menu looks correct now.

**Comment by zebapy** [comment]
Should I be seeing the flowchart on that web forms page or do you have it set up elsewhere?

**Comment by imcbride** [comment]
> 
> 
> Should I be seeing the flowchart on that web forms page or do you have it set up elsewhere?

It's at the bottom of the page ;)

**Comment by zebapy** [comment]
I'm not seeing it in chrome / logged out. 

Screenshot 2020-05-01 16 56 27

**Comment by imcbride** [comment]
The flowchart content wasn't published. I've fixed that. Let me know when you're comfortable with this being merged.

**Comment by zebapy** [comment]
Ok I noticed some css and js issues I'll jump on now.

**Comment by zebapy** [comment]
I'll merge this into dev and then look at merging into master since there may be other dev changes that should ship.

**Pull request merged**
