### PR TITLE
Middlebury header updates and school top level

### PR DESCRIPTION
**Pull request by imcbride**
I'm adding this so I have an easy visual reference for the recent changes.

### CODE REVIEW

**Comment by zebapy** [comment]
Ok. To reiterate, the main things to look at are the updated midd-header, school-header, and school-top-level. Events and profiles are WIP.

**Comment by imcbride** [comment]
Thanks for the clarification. To put this to visuals, am I right that:

http://saw.middlebury.edu/~imcbride/midd-frontend/dist/anchor-basic-content.html shows the desired midd-header

http://saw.middlebury.edu/~imcbride/midd-frontend/dist/school-basic-content.html shows the desired school-header

And is there a corresponding dist file for the school-top-level?

**Comment by zebapy** [comment]
Those look incorrect. 

Here's school top level + new school header http://saw.middlebury.edu/~zpykosz/midd-frontend/dist/school-top-level.html

And updated Big M header http://saw.middlebury.edu/~zpykosz/midd-frontend/dist/anchor-basic-content.html

**Comment by imcbride** [comment]
Got it, thanks. Somehow I had the master branch checked out in my development copy.

**Pull request merged**
