### PR TITLE
Nested event filters

### PR DESCRIPTION
**Pull request by adamfranco**
Add nested filters for hierarchical event taxonomies.

It turns out that the sponsoring organizations are a big list of items organized into groups (Academic Departments, Administrative Orgs, and Student Orgs). To make this list readable, indenting the child terms seems like a good bet, but I want to run this by you for design or coding practice feedback.

### CODE REVIEW

**Comment by adamfranco** [comment]
On second thought (after getting this working with the actual data, see screen-shot below), the list of options is probably too big to be usable even with nesting and should just be eliminated. We could merge the PR if it seems useful, but I'm happy to just to close without merging and leave the branch and PR here in closed state in case we encounter this need in the future. 

For future reference, the Drupal **Better Exposed Filters** module does to hierarchical select-all when clicking on a parent item, so the UI is pretty usable in that way. 

Events_Events_-_2020-10-13_08 44 24

**Comment by imcbride** [comment]
From the style perspective, I don't see any issues, but there should be an association between the parent item and the child items so that they are distinguishable for a user who can't view the nesting. Of the examples here, the third with aria-labelledby might be the easiest to implement.

https://www.w3.org/TR/2016/WD-wai-aria-practices-1.1-20160317/examples/checkbox/checkbox-2.html

**Comment by adamfranco** [comment]
Thanks for the feedback, Ian.

**Comment by Aterkel** [comment]
Screen shot of what I was thinking could be a good approach too
Screen Shot 2020-10-13 at 10 04 23 AM
 nesting.

**Comment by adamfranco** [comment]
Thanks, Ari! Am I interpreting this correctly as just the addition of the vertical line and the amount of indentation? Any other changes I should be sure to include?

**Comment by Aterkel** [comment]
Here is the screen shot with the amount of spacing called out for how far the nested filters should indent. Let me know if you have any questions.
Screen Shot 2020-12-04 at 10 22 57 AM

**Pull request merged**
